  - name: install apache and php for Ubuntu servers
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php for Fedora server
    tags: apache,fedora,httpd
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Fedora"

  - name: start httpd (Fedora)
    tags: apache,fedora,httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "Fedora"

  - name: change email address for admin
    tags: apache,fedora,httpd
    lineinfile:
       path: /etc/httpd/conf/httpd.conf
       regexp: '^ServerAdmin'
       line: ServerAdmin rnixon20@gmail.com
    when: ansible_distribution == "Fedora"
    register: httpd

  - name: restart httpd (Fedora)
    tags: apache,fedora,httpd
    service:
      name: httpd
      state: restarted
    when: httpd.changed

  - name: copy default html file for website
    tags: apache,apache2,http
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
